### PR TITLE
Handle invite to existing conference

### LINKED ISSUE #1373: handle crashes after group invites
Suppose A invites B to a group, B accepts, but then A crashes without saving. 
B then saves and leaves the group. B has no friend other than A in the group.
Then once A and B restart, B will not be able to rejoin the group because A 
does not consider B to be an offline peer in the group. Worse, A will not be 
able to reinvite B to the group -- B will ignore the invitation because B 
considers themself to be in the group.

### PR DESCRIPTION
**Pull request by zugz**
Fixes #1373.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1374)

### CODE REVIEW

File: toxcore/group.c [hunk 1]
```diff
@@ -1987,24 +2032,28 @@ static void handle_friend_invite_packet(Messenger *m, uint32_t friendnumber, con
...
-            unsigned int tries = 0;
+            uint16_t peer_number;
 
-            while (get_peer_index(g, peer_number) != -1 || get_frozen_index(g, peer_number) != -1) {
+            if (member) {
+                net_unpack_u16(data + 1 + sizeof(uint16_t) * 2 + 1 + GROUP_ID_LENGTH, &peer_number);
+            } else {
+                /* TODO(irungentoo): what if two people enter the group at the
+                 * same time and
+                   are given the same peer_number by different nodes? */
```
Comment (iphydf) [inline toxcore/group.c]: nit: comment formatting
