### PR TITLE
fix: potential freeing of an immutable static buffer

### LINKED ISSUE #1967: Potential freeing of an immutable static buffer

### PR DESCRIPTION
**Pull request by nurupo**
strerror_r() has two versions: GNU-specific and XSI-compliant. The XSI
version always stores the string in the provided buffer, but the GNU
version might store it in the provided buffer or it might use some
immutable static buffer instead. Since we always free the error string,
we might end up freeing the immutable static buffer.

https://man7.org/linux/man-pages/man3/strerror.3.html

Fixes #1967

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1948)

### CODE REVIEW

File: toxcore/network.c [hunk 1]
```diff
@@ -1725,7 +1725,17 @@ char *net_new_strerror(int error)
 #else
     char *str = (char *)malloc(256);
 #ifdef _GNU_SOURCE
-    str = strerror_r(error, str, 256);
+    char *retstr = strerror_r(error, str, 256);
+
+    if (retstr != str) {
+        const size_t retstr_len = strlen(retstr) + 1;
+        const size_t copy_len = retstr_len > 256 ? 256 : retstr_len;
```
Comment (iphydf) [inline toxcore/network.c:1732]: min_u32 maybe?

**Review by iphydf — CHANGES_REQUESTED** [review]

File: toxcore/network.c (hunk 1 above)
Comment (nurupo) [reply toxcore/network.c:1732]: Aha, so we do have a min macro. Actually, it's not even a macro but a function. Feels a bit weird treating `size_t` as `uint32_t`, but I guess it works...

**Review by JFreegman — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1948)* status: 2 change requests, 0 of 1 approvals obtained (waiting on @iphydf and @nurupo)

___
*[toxcore/network.c, line 1736 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1948#-MuvKoSx-zAetf48l7te:-MuvKoSx-zAetf48l7tf:bruvnft) ([raw file](https://github.com/toktok/c-toxcore/blob/260ecbe038d3c04f03dae842a6a08014092ee1ea/toxcore/network.c#L1736)):*
> ```C
>         // data in the middle of str for some inexplicable reason.
>         memmove(str, retstr, copy_len);
>         str[copy_len] = '\0';
> ```

If `copy_len` is equal to 256 it will overflow the `str` buffer. This is because you only allocate 256 bytes to str, which includes the null terminating byte.

In order to make this code more clear I'd use a constant in place of `256`, and allocate the buffer with a + 1 byte for the null: 
`#define MAX_LEN 256`
`char *str = malloc(MAX_LEN + 1)`

Then null termination is straight forward: `str[MAX_LEN] = '\0'`

**Comment by nurupo** [comment]
___
*[toxcore/network.c, line 1736 at r2](https://reviewable.io/reviews/toktok/c-toxcore/1948#-MuvKoSx-zAetf48l7te:-MuxeBvW-qm6v0A94SfS:b-896fix) ([raw file](https://github.com/toktok/c-toxcore/blob/260ecbe038d3c04f03dae842a6a08014092ee1ea/toxcore/network.c#L1736)):*
<details><summary><i>Previously, JFreegman wrote…</i></summary><blockquote>

If `copy_len` is equal to 256 it will overflow the `str` buffer. This is because you only allocate 256 bytes to str, which includes the null terminating byte.

In order to make this code more clear I'd use a constant in place of `256`, and allocate the buffer with a + 1 byte for the null: 
`#define MAX_LEN 256`
`char *str = malloc(MAX_LEN + 1)`

Then null termination is straight forward: `str[MAX_LEN] = '\0'`

</blockquote></details>

Done.

**Review by JFreegman — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1948)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)

**Review by iphydf — APPROVED** [review]

File: toxcore/network.c [hunk 2]
```diff
@@ -1745,7 +1745,17 @@ char *net_new_strerror(int error)
 #else
     char *str = (char *)malloc(256);
```
Comment (iphydf) [inline toxcore/network.c:1746]: Can you also add a null check?

**Review by iphydf — CHANGES_REQUESTED** [review]

**Review by iphydf — APPROVED** [review]

File: toxcore/network.c [hunk 3]
```diff
@@ -1745,7 +1745,17 @@ char *net_new_strerror(int error)
...
 #ifdef _GNU_SOURCE
-    str = strerror_r(error, str, 256);
+    char *retstr = strerror_r(error, str, 256);
+
+    if (retstr != str) {
```
Comment (iphydf) [inline toxcore/network.c:1750]: Maybe we should do this differently: allocate a buffer on the stack and then copy it into `str`, unconditionally. That way we can avoid this non-portable pointer compare.

**Review by iphydf — CHANGES_REQUESTED** [review]

File: toxcore/network.c (hunk 2 above)
Comment (nurupo) [reply toxcore/network.c:1746]: Done.

File: toxcore/network.c (hunk 3 above)
Comment (nurupo) [reply toxcore/network.c:1755]: I have no idea what you are saying. Why is this pointer comparison non-portable? How a stack buffer would help when `strerror_r()` is allowed to return an internal buffer instead of using our stack buffer, so we would have the same issue over again?

Comment (iphydf) [reply toxcore/network.c:1758]: Pointers can only be compared if they are pointing within the same allocation. E.g.:

```c
char a[2];
char b[2];
if (&a[0] == &a[1]) ... // OK
if (&a[0] == &b[0]) ... // UB

// Similarly:
char a[2];
char *b = malloc(2);
if (&a[0] == b) ... // UB

// Or equally:
char *a = malloc(2);
char *b = malloc(2);
if (a == b) ... // UB
```

We can avoid the problem by doing:

```c
#define STRERROR_BUF_SIZE 256
char buf[STRERROR_BUF_SIZE];
const char *retstr = strerror_r(error, buf, sizeof(buf));

const size_t len = strlen(retstr);
assert(len < STRERROR_BUF_SIZE);  // can this happen? probably need a test to make sure it can't
char *str = (char *)malloc(len);
if (str != nullptr) {
  memcpy(str, retstr, len + 1); // copy including null terminator
}
return str;
#undef STRERROR_BUF_SIZE
```

Comment (nurupo) [reply toxcore/network.c:1758]: If you want to avoid doing `retstr != str` comparison for some odd reason (how is comparing two `char *` is non-portable?), it can be removed as it is and the code would still be correct. There is no need to add any extra buffer. The comparison is in there just to avoid doing a useless `memmove(str, str, _)` in case `strerror_r()` stored the string in our buffer.

**Review by iphydf — APPROVED** [review]
