### PR TITLE
fix: out-of-memory condition by corrupted save file

### LINKED ISSUE #2083: Tox save file format/loader doesn't limit or check the number of frozen peers
A *.tox save file with an excessive number of frozen peers might lead to out-of-memory issues:
https://github.com/TokTok/c-toxcore/runs/5266641816?check_suite_focus=true#step:5:479

Relevant line: https://github.com/TokTok/c-toxcore/blob/master/toxcore/group.c#L3426

I guess in practice the file length is bounded, but our implementation doesn't check that.

The question is, do we want a hardcoded limit on that value? Or do we just use a few of the frozen peers and ignore the rest?

### PR DESCRIPTION
**Pull request by sudden6**
Don't allocate the memory trusting the values in a toxsave file.

Fixes #2083

Found with https://github.com/TokTok/c-toxcore/runs/5266641816?check_suite_focus=true#step:5:479

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/2084)

### CODE REVIEW

File: toxcore/group.c [hunk 1]
```diff
@@ -3460,6 +3451,14 @@ static uint32_t load_group(Group_c *g, const Group_Chats *g_c, const uint8_t *da
             return 0;
         }
 
+        // This is inefficient, but allows us to check data consistency before allocating memory
+        g->frozen = (Group_Peer *)realloc(g->frozen, (j + 1) * sizeof(Group_Peer));
+
+        if (g->frozen == nullptr) {
+            // Memory allocation failure
```
Comment (iphydf) [inline toxcore/group.c:3458]: Memory leak: realloc doesn't free on failure.

**Review by iphydf — CHANGES_REQUESTED** [review]

File: toxcore/group.c (hunk 1 above)
Comment (sudden6) [reply toxcore/group.c:3458]: This is handled in the cleanup code in line 3572

Comment (iphydf) [reply toxcore/group.c:3458]: `g->frozen` will be `nullptr` and `free` will be a no-op. Where do you keep track of the old pointer that was passed to `realloc`?

Comment (sudden6) [reply toxcore/group.c:3458]: I see, should be fixed now.

**Review by iphydf — APPROVED** [review]
