### PR TITLE
Fix using uninitialized mutex on call end

### LINKED ISSUE #1194: Cancelling unanswered toxav call locks uninitialied mutex
*Edit:* My apologies for the initial bug report, I thought the scope of this problem was much larger and was only being shown on MSVC.

When we create a toxav call we do not initialize any of our mutexes until we activate the call. If we then cancel the call we lock/unlock an uninitialized mutex. On MSVC this results in a segfault due to the pthread_mutex_t type being a typedeffed pointer.

Example in the following image.

image

Note that mutex[0] == NULL. Visual studio made a mistake in where it places the (X) in this image, the access violation occurs in pthread_mutex_unlock.

### PR DESCRIPTION
**Pull request by sphaerophoria**
Closes #1194

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/c-toxcore/1195)

### CODE REVIEW

File: toxav/toxav.c [hunk 1]
```diff
@@ -1180,10 +1180,19 @@ ToxAVCall *call_new(ToxAV *av, uint32_t friend_number, Toxav_Err_Call *error)
     call->av = av;
     call->friend_number = friend_number;
 
+    if (create_recursive_mutex(call->mutex))
```
Comment (iphydf) [inline toxav/toxav.c]: `if (...) {`
